name: govpulse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 2.25.4
  firebase_auth: 4.16.0
  google_sign_in: 6.2.1
  lottie: ^2.7.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0
  http: ^1.2.0
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2
  dotted_border: ^2.0.0
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.11.0
  image: ^4.1.7
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  android_intent_plus: ^4.0.0
  image_picker: ^1.1.2
  video_thumbnail: ^0.5.3
  video_player: ^2.9.2
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# Force a stable google_maps_flutter_android that does NOT have
# the broken HeatmapController.java / android-maps-utils 4.x issue
dependency_overrides:
  google_maps_flutter_android: 2.14.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/report/
    - assets/images/emergency/
    - assets/images/settings/
    - assets/images/idicons/
    - assets/images/idcards/
    - assets/images/verification/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.png"