org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --add-opens=java.base/java.lang=ALL-UNNAMED --enable-native-access=ALL-UNNAMED
kotlin.daemon.jvmargs=-Xmx4G
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.19.10-hotspot
android.useAndroidX=true
MAPS_API_KEY=AIzaSyBPB83g_u1ecxDzMjB0yRv8Lqg07oeGwhQ