// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOW2r4TA5Wm3JkPVnqL0OVOld2c7fUmCw',
    appId: '1:778312829212:web:bfee49c38d432c860152d9',
    messagingSenderId: '778312829212',
    projectId: 'prototype-8d371',
    authDomain: 'prototype-8d371.firebaseapp.com',
    storageBucket: 'prototype-8d371.firebasestorage.app',
    measurementId: 'G-ZEQYBV59HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQfk5acL8myb1OyWQU4n29O8wXL_KgHWc',
    appId: '1:778312829212:android:19e0857f840a4f190152d9',
    messagingSenderId: '778312829212',
    projectId: 'prototype-8d371',
    storageBucket: 'prototype-8d371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyInWnSjGfqkFVfirts5VxkfU6u3dzlzs',
    appId: '1:778312829212:ios:0cac3c77af451dff0152d9',
    messagingSenderId: '778312829212',
    projectId: 'prototype-8d371',
    storageBucket: 'prototype-8d371.firebasestorage.app',
    iosBundleId: 'com.example.govpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyInWnSjGfqkFVfirts5VxkfU6u3dzlzs',
    appId: '1:778312829212:ios:0cac3c77af451dff0152d9',
    messagingSenderId: '778312829212',
    projectId: 'prototype-8d371',
    storageBucket: 'prototype-8d371.firebasestorage.app',
    iosBundleId: 'com.example.govpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOW2r4TA5Wm3JkPVnqL0OVOld2c7fUmCw',
    appId: '1:778312829212:web:27cc77518ceef8390152d9',
    messagingSenderId: '778312829212',
    projectId: 'prototype-8d371',
    authDomain: 'prototype-8d371.firebaseapp.com',
    storageBucket: 'prototype-8d371.firebasestorage.app',
    measurementId: 'G-LRM3F7M71M',
  );
}
