// ════════════════════════════════════════════════════════════════════════════
//  Deployment-time configuration
//
//  Values that differ between a developer's machine and the deployed site, and
//  that therefore must NOT be hardcoded at a call site. Everything here is read
//  from `--dart-define`, with a default that keeps a local run working.
//
//    flutter build web \
//      --dart-define=SCAN_BASE_URL=https://govpulse.aparri.gov.ph \
//      --dart-define=LGU_MAYOR_NAME="Hon. Juan Dela Cruz"
// ════════════════════════════════════════════════════════════════════════════

class AppConfig {
  const AppConfig._();

  /// Origin the endorsement QR code points at.
  ///
  /// This is the one value that MUST be set for a real deployment. The QR is
  /// printed onto a paper letter and scanned by an agency's phone camera, which
  /// has no idea what "localhost" means — so a letter generated with the
  /// default is only ever useful on the machine that made it.
  ///
  /// No trailing slash; [scanUrl] adds the separator.
  ///
  /// The default is the live production origin, not localhost, so a letter
  /// generated by ANY build carries a scannable code. A dart-define still
  /// overrides it for a staging deploy.
  static const String scanBaseUrl = String.fromEnvironment(
    'SCAN_BASE_URL',
    defaultValue: 'https://gov-pulse-rose.vercel.app',
  );

  /// Full URL encoded into the QR for [token].
  ///
  /// CLEAN-PATH, as of the URL cutover. Both halves that form needs are now in
  /// place: `usePathUrlStrategy()` runs in main.dart, and vercel.json rewrites
  /// every extension-less path to /index.html, so a reload of this URL reaches
  /// the app rather than the host's own 404.
  ///
  /// ── Codes printed before the cutover ──────────────────────────────────────
  /// Letters already in circulation carry the old `/#/scan/<token>` form, and
  /// those DO stop resolving: PathUrlStrategy reads the pathname and discards
  /// the fragment, so the app sees `/` and opens the landing page rather than
  /// the scan screen. Reprint any letter that still matters. This was a
  /// deliberate, accepted trade — the codes in circulation were test prints.
  static String scanUrl(String token) => '$scanBaseUrl/scan/$token';

  // ── Endorsement letter ────────────────────────────────────────────────────
  // Printed on an official document over the Mayor's signature line, so these
  // are deployment configuration rather than constants in a PDF builder.

  static const String lguName = 'Municipality of Aparri';
  static const String province = 'Province of Cagayan';
  static const String republic = 'Republic of the Philippines';

  static const String mayorName = String.fromEnvironment(
    'LGU_MAYOR_NAME',
    defaultValue: 'Hon. Dominador Ambo Dayag',
  );

  static const String mayorTitle = 'Municipal Mayor';

  /// Asset path for the municipal seal on the letterhead.
  ///
  /// ⚠ TEMPORARY: this is the GovPulse app logo, NOT the official municipal
  /// seal of Aparri. It stands in so the letterhead renders something real;
  /// replace it with the actual seal before these letters go to an agency.
  ///
  /// Must be PNG or JPEG — the `pdf` package decodes only those, so the WebP
  /// original could not be used directly (hence the converted `.png` beside
  /// it). Set to empty to fall back to the drawn placeholder ring.
  ///
  /// Files sitting directly in `assets/images/` need no pubspec change: that
  /// directory is already registered. Only a NEW subdirectory would.
  ///
  /// Prefer artwork that reads in BLACK AND WHITE — the letter is designed to
  /// photocopy and fax cleanly, and a colour logo greys out unpredictably.
  static const String sealAssetPath = String.fromEnvironment(
    'LGU_SEAL_ASSET',
    // The real municipal seal of Aparri. This was the GovPulse APP LOGO until
    // 2026-08-31 — a product mark standing in for a government crest on a
    // letter issued over the Mayor's signature, which is the one place a
    // vendor logo has no business being. It was always meant as a placeholder;
    // the seal arrived, so it is gone.
    //
    // ⚠ PNG, not the aparri.webp beside it. The `pdf` package decodes PNG and
    // JPEG only — handed a WebP it throws, _loadSeal swallows it, and the
    // letter quietly falls back to the drawn placeholder ring. That failure is
    // completely silent: the export succeeds, the file is valid, and the only
    // symptom is a government letter going out with "LGU APARRI" in a circle
    // where the crest should be. Measured: the WebP build produced a 12KB PDF
    // against 304KB with the seal actually embedded.
    //
    // 220x220 is ~283dpi at the 56pt the letterhead draws it, which is ample
    // for print. Keep any replacement PNG or JPEG.
    defaultValue: 'assets/images/aparri_seal.png',
  );

  // ── Error reporting ─────────────────────────────────────────────────────
  // See core/services/error_reporting.dart.

  /// Sentry DSN. Empty disables reporting entirely.
  ///
  /// DELIBERATELY EMPTY BY DEFAULT, unlike [scanBaseUrl] above. A DSN is not a
  /// secret — it is a write-only ingest key baked into every shipped client —
  /// but a default would send a developer's local crashes, and every widget
  /// test's deliberately-thrown exception, into the production issue feed. The
  /// signal there is only worth anything if everything in it came from a real
  /// deployment.
  ///
  ///   flutter build web --release --dart-define=SENTRY_DSN=https://…@…ingest.de.sentry.io/…
  static const String sentryDsn = String.fromEnvironment('SENTRY_DSN');

  /// Which deployment an event came from: `production`, `staging`, `dev`.
  ///
  /// Sentry filters and alerts on this, so a staging build sharing the
  /// production DSN stays separable rather than polluting it.
  static const String sentryEnvironment = String.fromEnvironment(
    'SENTRY_ENVIRONMENT',
    defaultValue: 'production',
  );

  /// Whether error reporting is configured at all.
  static bool get errorReportingEnabled => sentryDsn.isNotEmpty;
}
