// ════════════════════════════════════════════════════════════════════════════
//  Deployment-time configuration
//
//  Values that differ between a developer's machine and the deployed site, and
//  that therefore must NOT be hardcoded at a call site. Everything here is read
//  from `--dart-define`, with a default that keeps a local run working.
//
//    flutter build web \
//      --dart-define=SCAN_BASE_URL=https://govpulse.aparri.gov.ph \
//      --dart-define=LGU_MAYOR_NAME="Hon. Juan Dela Cruz"
// ════════════════════════════════════════════════════════════════════════════

class AppConfig {
  const AppConfig._();

  /// Origin the endorsement QR code points at.
  ///
  /// This is the one value that MUST be set for a real deployment. The QR is
  /// printed onto a paper letter and scanned by an agency's phone camera, which
  /// has no idea what "localhost" means — so a letter generated with the
  /// default is only ever useful on the machine that made it.
  ///
  /// No trailing slash; [scanUrl] adds the separator.
  ///
  /// The default is the live production origin, not localhost, so a letter
  /// generated by ANY build carries a scannable code. A dart-define still
  /// overrides it for a staging deploy.
  static const String scanBaseUrl = String.fromEnvironment(
    'SCAN_BASE_URL',
    defaultValue: 'https://gov-pulse-rose.vercel.app',
  );

  /// Full URL encoded into the QR for [token].
  ///
  /// HASH-ROUTED ON PURPOSE. Flutter web's default URL strategy is hash-based,
  /// and a hash URL is served correctly by any static host with no
  /// configuration at all — the whole path is `/`, so a deep link cannot 404 and
  /// a refresh on the scan page cannot break.
  ///
  /// The clean-path alternative (`/scan/<token>`) needs BOTH `usePathUrlStrategy()`
  /// at startup AND a server rewrite sending every unmatched path to
  /// /index.html. `firebase.json` currently has no `hosting` block at all, so
  /// today that form would 404 the instant anyone reloaded. If you add hosting
  /// with a `"rewrites": [{"source": "**", "destination": "/index.html"}]` rule
  /// and call usePathUrlStrategy(), drop the `/#` below and nothing else here
  /// changes.
  static String scanUrl(String token) => '$scanBaseUrl/#/scan/$token';

  // ── Endorsement letter ────────────────────────────────────────────────────
  // Printed on an official document over the Mayor's signature line, so these
  // are deployment configuration rather than constants in a PDF builder.

  static const String lguName = 'Municipality of Aparri';
  static const String province = 'Province of Cagayan';
  static const String republic = 'Republic of the Philippines';

  static const String mayorName = String.fromEnvironment(
    'LGU_MAYOR_NAME',
    defaultValue: 'Hon. Dominador Ambo Dayag',
  );

  static const String mayorTitle = 'Municipal Mayor';

  /// Asset path for the municipal seal on the letterhead.
  ///
  /// ⚠ TEMPORARY: this is the GovPulse app logo, NOT the official municipal
  /// seal of Aparri. It stands in so the letterhead renders something real;
  /// replace it with the actual seal before these letters go to an agency.
  ///
  /// Must be PNG or JPEG — the `pdf` package decodes only those, so the WebP
  /// original could not be used directly (hence the converted `.png` beside
  /// it). Set to empty to fall back to the drawn placeholder ring.
  ///
  /// Files sitting directly in `assets/images/` need no pubspec change: that
  /// directory is already registered. Only a NEW subdirectory would.
  ///
  /// Prefer artwork that reads in BLACK AND WHITE — the letter is designed to
  /// photocopy and fax cleanly, and a colour logo greys out unpredictably.
  static const String sealAssetPath = String.fromEnvironment(
    'LGU_SEAL_ASSET',
    // The real municipal seal of Aparri. This was the GovPulse APP LOGO until
    // 2026-08-31 — a product mark standing in for a government crest on a
    // letter issued over the Mayor's signature, which is the one place a
    // vendor logo has no business being. It was always meant as a placeholder;
    // the seal arrived, so it is gone.
    //
    // ⚠ PNG, not the aparri.webp beside it. The `pdf` package decodes PNG and
    // JPEG only — handed a WebP it throws, _loadSeal swallows it, and the
    // letter quietly falls back to the drawn placeholder ring. That failure is
    // completely silent: the export succeeds, the file is valid, and the only
    // symptom is a government letter going out with "LGU APARRI" in a circle
    // where the crest should be. Measured: the WebP build produced a 12KB PDF
    // against 304KB with the seal actually embedded.
    //
    // 220x220 is ~283dpi at the 56pt the letterhead draws it, which is ample
    // for print. Keep any replacement PNG or JPEG.
    defaultValue: 'assets/images/aparri_seal.png',
  );
}
